version: "3"

services:
  engine:
    image: engine:latest
    # image: ollama/ollama:latest
    container_name: engine
    pull_policy: always
    tty: true
    volumes:
      - ./volumes/engine:/root/.ollama
    restart: unless-stopped

  web:
    image: web:latest
    # image: ghcr.io/open-webui/open-webui:main
    container_name: web
    depends_on:
      - engine
    environment:
      - 'OLLAMA_BASE_URL=http://engine:11434'
      - 'WEBUI_SECRET_KEY='
    ports:
      - 80:8080
    volumes:
      - ./volumes/web:/app/backend/data
    # Я хз что это
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
