version: "3"

vars:
  PIP_PATH: "./venv/bin/pip"
  PYTHON_PATH: "./venv/bin/python"
  ANSBILE_PATH: "./venv/bin/ansible"
  PLAYBOOK_PATH: "./venv/bin/ansible-playbook"

tasks:
  default:
    cmds:
      - task --list-all
    silent: true

  init:
    desc: "Local ansbile installation"
    cmds:
      - python3 -m venv venv
      - "{{.PIP_PATH}} install -r requirements.txt"
      - ./venv/bin/ansible-galaxy collection install community.docker
      # - docker network create proxynet
      # - docker network create llmnet

  ping:
    desc: "Ping inventory.ini"
    cmds:
      - "{{.ANSBILE_PATH}} -m ping all"

  playbook:
    desc: "Run all playbooks"
    cmds:
      - "{{.PLAYBOOK_PATH}} playbook.yaml \
        --tags all \
        --extra-vars vars.yaml \
        -vv"

  docker-pull:
    desc: "Pull and save containers localy if not exists"
    cmds:
      - |
        if [ ! -f "./engine.tar.gz" ]; then
          docker pull ollama/ollama:latest
          docker save ollama/ollama:latest | gzip > engine.tar.gz
        fi
        if [ ! -f "./web.tar.gz" ]; then
          docker pull ghcr.io/open-webui/open-webui:main
          docker save ghcr.io/open-webui/open-webui:main | gzip > web.tar.gz
        fi
