---
- name: Deploy Apps
  hosts: all
  become: true
  tasks:
    - name: Install python3-requests
      apt:
        name: python3-requests
        state: present
        update_cache: yes
    - name: Create custom Docker network proxynet
      community.docker.docker_network:
        name: proxynet
        state: present
    - name: Create custom Docker network llmnet
      community.docker.docker_network:
        name: llmnet
        state: present
    - name: docker-compose up
      community.docker.docker_compose_v2:
        project_src: "{{ app_path }}"
        state: present
