---
- name: Post install
  hosts: all
  become: true
  tasks:
    - name: Remove the package
      apt:
        name:
          - vim
          - vim-common
          - vim-runtime
          - vim-tiny
          - nano
          - vi
          - net-tools
          - curl
          - traceroute
          - syslog-ng-mod-add-contextual-data
          - syslog-ng-mod-amqp
          - syslog-ng-mod-examples
          - syslog-ng-mod-extra
          - syslog-ng-mod-geoip2
          - syslog-ng-mod-geoip
          - syslog-ng-mod-getent
          - syslog-ng-mod-graphite
          - syslog-ng-mod-journal
          - syslog-ng-mod-map-value-pairs
          - syslog-ng-mod-mongodb
          - syslog-ng-mod-pacctformat
          - syslog-ng-mod-python
          - syslog-ng-mod-redis
          - syslog-ng-mod-riemann
          - syslog-ng-mod-smtp
          - syslog-ng-mod-snmptrapd-parser
          - syslog-ng-mod-sql
          - syslog-ng-mod-stardate
          - syslog-ng-mod-stomp
          - syslog-ng-mod-tag-parser
          - syslog-ng-mod-xml-parser
          - gettext
          - info
          - man-db
          - nmap
        state: absent

    - name: Autoremove unused dependencies
      apt:
        autoremove: yes
