---
- name: Pre install
  hosts: all
  become: true
  tasks:
    - name: Enable IP forwarding temporarily
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        state: present
        reload: yes
