---
- name: Install docker requirements
  apt:
    name:
      - docker.io
      - docker-compose
    state: present
    update_cache: yes

- name: Pull docker images for rename it
  docker_image:
    name: "{{ ollama_tag }}"
    source: pull

- name: Pull docker images for rename it
  docker_image:
    name: "{{ web_tag }}"
    source: pull

- name: Rename (tag) the Docker image
  docker_image:
    name: "{{ ollama_tag }}"
    tag: llm-engine:latest
    source: local

- name: Rename (tag) the Docker image
  docker_image:
    name: "{{ web_tag }}"
    tag: llm-web:latest
    source: local

- name: Ensure the target docker directory exists
  file:
    path: "{{ app_path }}"
    state: directory
    mode: "0700"

- name: Copy ./docker-compose.yaml to {{ app_path }}/docker-compose.yaml"
  copy:
    src: "./docker-compose.yaml"
    dest: "{{ app_path }}/docker-compose.yaml"
    mode: "0600"

- name: docker-compose up
  community.docker.docker_compose:
    project_src: "{{ app_path }}"
    state: present

- name: Remove the package
  apt:
    name:
      - vim
      - vim-common
      - vim-runtime
      - vim-tiny
      - nano
      - vi
      - net-tools
      - curl
      - traceroute
      - syslog-ng-mod-add-contextual-data
      - syslog-ng-mod-amqp
      - syslog-ng-mod-examples
      - syslog-ng-mod-extra
      - syslog-ng-mod-geoip2
      - syslog-ng-mod-geoip
      - syslog-ng-mod-getent
      - syslog-ng-mod-graphite
      - syslog-ng-mod-journal
      - syslog-ng-mod-map-value-pairs
      - syslog-ng-mod-mongodb
      - syslog-ng-mod-pacctformat
      - syslog-ng-mod-python
      - syslog-ng-mod-redis
      - syslog-ng-mod-riemann
      - syslog-ng-mod-smtp
      - syslog-ng-mod-snmptrapd-parser
      - syslog-ng-mod-sql
      - syslog-ng-mod-stardate
      - syslog-ng-mod-stomp
      - syslog-ng-mod-tag-parser
      - syslog-ng-mod-xml-parser
      - gettext
      - info
      - man-db
      - nmap
    state: absent

- name: Autoremove unused dependencies
  apt:
    autoremove: yes
